# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('scheme', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
                ('method', models.CharField(max_length=250)),
                ('content_type', models.CharField(max_length=250)),
                ('is_viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('jabber', models.EmailField(max_length=254)),
                ('skype', models.CharField(max_length=50)),
                ('other_contacts', models.TextField(blank=True, default=None, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/')),
            ],
        ),
    ]
