# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('jabber', models.EmailField(max_length=254)),
                ('skype', models.CharField(max_length=50)),
                ('other_contacts', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
