# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='photo',
            field=models.ImageField(blank=True, height_field=200, upload_to='user_photo/', width_field=200),
        ),
    ]
