# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_auto_20170620_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
