# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_auto_20170620_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='width_field',
            field=models.IntegerField(default=200),
        ),
    ]
