# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_userinformation_width_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='width_field',
        ),
    ]
